title: Westfire Records
email: info@westfirerecords.com
description: Somos una familia de músicos y artistas de la Viña Escazú, Costa Rica. Expresamos la grandeza y el amor de Dios mediante música y otras expresiones artísticas
default_img: https://dato-images.imgix.net/489/1481269466-1479049450-BannerWF.jpg?fit=crop&w=1000
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.westfirerecords.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

social:
  - network: facebook
    url: "https://www.facebook.com/westfirerecords"
  - network: instagram
    url: "https://www.instagram.com/westfirerecords/"
  - network: youtube
    url: "https://www.youtube.com/channel/UCwlBb2u2CRou-q5zIcrOH7Q"

# Build settings
markdown: kramdown

#collections
collections:
  artistas:
    permalink: /artistas/:path/
    output: true
  albums:
    output: true
  canciones:
    output: true
  videos:
    output: true

gems:
  - jekyll-sitemap

sass:
    style: compressed

array: []
